from __future__ import annotations

import io
import zipfile
from dataclasses import dataclass
from typing import Any, Literal


@dataclass(frozen=True)
class LatexZipExport:
    filename: str
    data: bytes


def _latex_escape(s: str) -> str:
    if s is None:
        return ""
    # Minimal LaTeX escaping for common resume text
    rep = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    out = []
    for ch in str(s):
        out.append(rep.get(ch, ch))
    return "".join(out)


_JAKE_RESUME_CLS = r"""
% Jake's Resume (minimal) - embedded for Overleaf upload
\ProvidesClass{resume}
\LoadClass[11pt]{article}
\usepackage[margin=0.75in]{geometry}
\usepackage{hyperref}
\usepackage{enumitem}
\usepackage{xcolor}
\usepackage{titlesec}
\usepackage{tabularx}
\usepackage{fontawesome5}
\setlist[itemize]{noitemsep, topsep=0pt, leftmargin=*}
\pagenumbering{gobble}
\definecolor{linkcolor}{RGB}{0,102,204}
\hypersetup{colorlinks=true, urlcolor=linkcolor}
\titleformat{\section}{\large\bfseries}{}{0em}{}[\titlerule]
\newcommand{\name}[1]{\centerline{\Huge \bfseries #1}}
\newcommand{\contact}[1]{\centerline{#1}}
\newcommand{\resumeSubheading}[4]{
  \begin{tabularx}{\textwidth}{X r}
    \textbf{#1} & #2 \\
    \textit{#3} & \textit{#4} \\
  \end{tabularx}
}
"""


def build_latex_main_tex(
    *,
    analysis: dict[str, Any],
    resume: dict[str, Any],
    mode: Literal["new_resume", "apply_changes"],
    latex_source: str | None = None,
) -> str:
    analysis_id = analysis.get("analysis_id") or "analysis"

    if mode == "apply_changes":
        if not latex_source or not latex_source.strip():
            raise ValueError("latex_source is required when mode=apply_changes")
        return latex_source

    extracted = resume.get("extracted") or {}
    skills = extracted.get("skills") or []
    education = extracted.get("education") or []
    experience = extracted.get("experience") or []

    suggestions = analysis.get("suggestions") or {}
    bullet_rewrites = (suggestions.get("bullet_rewrites") or [])[:3]
    projects_to_build = (suggestions.get("projects_to_build") or [])[:3]

    # Placeholder identity fields (user edits in Overleaf)
    name = "Your Name"
    contact = r"\href{mailto:you@email.com}{you@email.com} $|$ \href{https://linkedin.com/in/you}{linkedin.com/in/you} $|$ \href{https://github.com/you}{github.com/you}"

    skills_line = ", ".join(_latex_escape(s) for s in skills[:18]) if skills else ""

    edu_items = "\n".join(r"\item " + _latex_escape(e) for e in education[:6]) or r"\item [Add your education here]"
    exp_items = "\n".join(r"\item " + _latex_escape(e) for e in experience[:8]) or r"\item [Add your experience here]"

    proj_items = "\n".join(r"\item " + _latex_escape(p) for p in projects_to_build) or r"\item [Add projects here]"

    rewrite_items = ""
    if bullet_rewrites:
        rewrite_items = "\n".join(
            r"\item " + _latex_escape((b.get("after") or b.get("before") or "").strip())
            for b in bullet_rewrites
            if isinstance(b, dict)
        )

    main_tex = rf"""
\documentclass{{resume}}

\begin{{document}}
\name{{{_latex_escape(name)}}}
\contact{{{contact}}}

\section{{Summary}}
\begin{{itemize}}
  \item AI/ML-focused engineer with hands-on experience in LLM apps, RAG, and backend APIs. Tailored using ResumeAI analysis \texttt{{{_latex_escape(analysis_id)}}}.
\end{{itemize}}

\section{{Skills}}
\begin{{itemize}}
  \item {skills_line}
\end{{itemize}}

\section{{Experience}}
\begin{{itemize}}
{exp_items}
\end{{itemize}}

\section{{Education}}
\begin{{itemize}}
{edu_items}
\end{{itemize}}

\section{{Projects}}
\begin{{itemize}}
{proj_items}
\end{{itemize}}

"""

    if rewrite_items.strip():
        main_tex += rf"""
\section{{Tailored Bullets (Suggested)}}
\begin{{itemize}}
{rewrite_items}
\end{{itemize}}
"""

    main_tex += r"""
\end{document}
""".lstrip()

    return main_tex


def export_latex_zip(
    *,
    analysis: dict[str, Any],
    resume: dict[str, Any],
    mode: Literal["new_resume", "apply_changes"],
    latex_source: str | None = None,
) -> LatexZipExport:
    analysis_id = analysis.get("analysis_id") or "analysis"
    main_tex = build_latex_main_tex(
        analysis=analysis,
        resume=resume,
        mode=mode,
        latex_source=latex_source,
    )

    readme = f"""Overleaf upload instructions:
1) Go to https://www.overleaf.com/project/new
2) Upload this zip
3) Open main.tex and edit placeholders (name, contact, sections)

Generated by ResumeAI.
Analysis id: {analysis_id}
"""

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("main.tex", main_tex)
        zf.writestr("resume.cls", _JAKE_RESUME_CLS.strip() + "\n")
        zf.writestr("README.txt", readme)

    return LatexZipExport(filename=f"overleaf_{analysis_id}.zip", data=buf.getvalue())


